### ISSUE TITLE
[Mod submission]: Puffy's NPC's

### ISSUE THREAD

**Issue by P1uffy** [Voxelstice/niko-build-sandbox-mod-database#15]
### Roblox Model Link

https://www.roblox.com/library/11329047096/npc-mod

### Discord Username and Tag

Puffy#3710

### Mod Description

This mod essentialy adds npc's to the game. You can spawn robert and even spawn your friends players.

:spawnnpc [npc_name]
:spawnnpc custom [player_name]

### Mod Content

* NPC's

### Rules

- [X] I agree to follow the mod submission rules

**Comment by Voxelstice** [comment]
![image](https://user-images.githubusercontent.com/95834462/197184832-4c554b0e-116d-42f9-9acc-dd561d0c15dd.png)
i love this script name

The mod already seems to be added but niko forgot to close the issue so
