### ISSUE TITLE
nuclear bomb mod with some fart sounds!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by nikothegamer100** [Voxelstice/niko-build-sandbox-mod-database#8]
### Roblox Model Link

nuclear bomb mod with some fart sounds!!!!!!!!!!!!!!

### Discord Username and Tag

nuclear bomb mod with some fart sounds!!!!!!!!!!!!!!

### Mod Description

nuclear bomb mod with some fart sounds!!!!!!!!!!!!!!

### Mod Content

nuclear bomb mod with some fart sounds!!!!!!!!!!!!!!

### Rules

- [X] I agree to follow the mod submission rules

**Comment by Voxelstice** [comment]
You are my test subject for closing this issue
